// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: matchmaking_grpc.proto

package matchmaking_grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestRoomMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId_1    string                 `protobuf:"bytes,1,opt,name=player_id_1,json=playerId1,proto3" json:"player_id_1,omitempty"`
	PlayerId_2    string                 `protobuf:"bytes,2,opt,name=player_id_2,json=playerId2,proto3" json:"player_id_2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestRoomMessage) Reset() {
	*x = RequestRoomMessage{}
	mi := &file_matchmaking_grpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestRoomMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestRoomMessage) ProtoMessage() {}

func (x *RequestRoomMessage) ProtoReflect() protoreflect.Message {
	mi := &file_matchmaking_grpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestRoomMessage.ProtoReflect.Descriptor instead.
func (*RequestRoomMessage) Descriptor() ([]byte, []int) {
	return file_matchmaking_grpc_proto_rawDescGZIP(), []int{0}
}

func (x *RequestRoomMessage) GetPlayerId_1() string {
	if x != nil {
		return x.PlayerId_1
	}
	return ""
}

func (x *RequestRoomMessage) GetPlayerId_2() string {
	if x != nil {
		return x.PlayerId_2
	}
	return ""
}

type RoomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	ErrorMsg      *string                `protobuf:"bytes,2,opt,name=error_msg,json=errorMsg,proto3,oneof" json:"error_msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomResponse) Reset() {
	*x = RoomResponse{}
	mi := &file_matchmaking_grpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomResponse) ProtoMessage() {}

func (x *RoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_matchmaking_grpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomResponse.ProtoReflect.Descriptor instead.
func (*RoomResponse) Descriptor() ([]byte, []int) {
	return file_matchmaking_grpc_proto_rawDescGZIP(), []int{1}
}

func (x *RoomResponse) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *RoomResponse) GetErrorMsg() string {
	if x != nil && x.ErrorMsg != nil {
		return *x.ErrorMsg
	}
	return ""
}

type StartStreamingMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartStreamingMessage) Reset() {
	*x = StartStreamingMessage{}
	mi := &file_matchmaking_grpc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartStreamingMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartStreamingMessage) ProtoMessage() {}

func (x *StartStreamingMessage) ProtoReflect() protoreflect.Message {
	mi := &file_matchmaking_grpc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartStreamingMessage.ProtoReflect.Descriptor instead.
func (*StartStreamingMessage) Descriptor() ([]byte, []int) {
	return file_matchmaking_grpc_proto_rawDescGZIP(), []int{2}
}

type GameEndedEventMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pl1           string                 `protobuf:"bytes,1,opt,name=pl1,proto3" json:"pl1,omitempty"`
	Pl2           string                 `protobuf:"bytes,2,opt,name=pl2,proto3" json:"pl2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameEndedEventMsg) Reset() {
	*x = GameEndedEventMsg{}
	mi := &file_matchmaking_grpc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameEndedEventMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameEndedEventMsg) ProtoMessage() {}

func (x *GameEndedEventMsg) ProtoReflect() protoreflect.Message {
	mi := &file_matchmaking_grpc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameEndedEventMsg.ProtoReflect.Descriptor instead.
func (*GameEndedEventMsg) Descriptor() ([]byte, []int) {
	return file_matchmaking_grpc_proto_rawDescGZIP(), []int{3}
}

func (x *GameEndedEventMsg) GetPl1() string {
	if x != nil {
		return x.Pl1
	}
	return ""
}

func (x *GameEndedEventMsg) GetPl2() string {
	if x != nil {
		return x.Pl2
	}
	return ""
}

var File_matchmaking_grpc_proto protoreflect.FileDescriptor

const file_matchmaking_grpc_proto_rawDesc = "" +
	"\n" +
	"\x16matchmaking_grpc.proto\"T\n" +
	"\x12RequestRoomMessage\x12\x1e\n" +
	"\vplayer_id_1\x18\x01 \x01(\tR\tplayerId1\x12\x1e\n" +
	"\vplayer_id_2\x18\x02 \x01(\tR\tplayerId2\"W\n" +
	"\fRoomResponse\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12 \n" +
	"\terror_msg\x18\x02 \x01(\tH\x00R\berrorMsg\x88\x01\x01B\f\n" +
	"\n" +
	"_error_msg\"\x17\n" +
	"\x15StartStreamingMessage\"7\n" +
	"\x11GameEndedEventMsg\x12\x10\n" +
	"\x03pl1\x18\x01 \x01(\tR\x03pl1\x12\x10\n" +
	"\x03pl2\x18\x02 \x01(\tR\x03pl22\x82\x01\n" +
	"\vMatchMaking\x123\n" +
	"\vRequestRoom\x12\x13.RequestRoomMessage\x1a\r.RoomResponse\"\x00\x12>\n" +
	"\x0eStartStreamMsg\x12\x16.StartStreamingMessage\x1a\x12.GameEndedEventMsg0\x01B\x14Z\x12./matchmaking_grpcb\x06proto3"

var (
	file_matchmaking_grpc_proto_rawDescOnce sync.Once
	file_matchmaking_grpc_proto_rawDescData []byte
)

func file_matchmaking_grpc_proto_rawDescGZIP() []byte {
	file_matchmaking_grpc_proto_rawDescOnce.Do(func() {
		file_matchmaking_grpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_matchmaking_grpc_proto_rawDesc), len(file_matchmaking_grpc_proto_rawDesc)))
	})
	return file_matchmaking_grpc_proto_rawDescData
}

var file_matchmaking_grpc_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_matchmaking_grpc_proto_goTypes = []any{
	(*RequestRoomMessage)(nil),    // 0: RequestRoomMessage
	(*RoomResponse)(nil),          // 1: RoomResponse
	(*StartStreamingMessage)(nil), // 2: StartStreamingMessage
	(*GameEndedEventMsg)(nil),     // 3: GameEndedEventMsg
}
var file_matchmaking_grpc_proto_depIdxs = []int32{
	0, // 0: MatchMaking.RequestRoom:input_type -> RequestRoomMessage
	2, // 1: MatchMaking.StartStreamMsg:input_type -> StartStreamingMessage
	1, // 2: MatchMaking.RequestRoom:output_type -> RoomResponse
	3, // 3: MatchMaking.StartStreamMsg:output_type -> GameEndedEventMsg
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_matchmaking_grpc_proto_init() }
func file_matchmaking_grpc_proto_init() {
	if File_matchmaking_grpc_proto != nil {
		return
	}
	file_matchmaking_grpc_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_matchmaking_grpc_proto_rawDesc), len(file_matchmaking_grpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_matchmaking_grpc_proto_goTypes,
		DependencyIndexes: file_matchmaking_grpc_proto_depIdxs,
		MessageInfos:      file_matchmaking_grpc_proto_msgTypes,
	}.Build()
	File_matchmaking_grpc_proto = out.File
	file_matchmaking_grpc_proto_goTypes = nil
	file_matchmaking_grpc_proto_depIdxs = nil
}
