// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: matchmaking_grpc.proto

package matchmaking_grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MatchMaking_RequestRoom_FullMethodName    = "/MatchMaking/RequestRoom"
	MatchMaking_StartStreamMsg_FullMethodName = "/MatchMaking/StartStreamMsg"
)

// MatchMakingClient is the client API for MatchMaking service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MatchMakingClient interface {
	RequestRoom(ctx context.Context, in *RequestRoomMessage, opts ...grpc.CallOption) (*RoomResponse, error)
	StartStreamMsg(ctx context.Context, in *StartStreamingMessage, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GameEndedEventMsg], error)
}

type matchMakingClient struct {
	cc grpc.ClientConnInterface
}

func NewMatchMakingClient(cc grpc.ClientConnInterface) MatchMakingClient {
	return &matchMakingClient{cc}
}

func (c *matchMakingClient) RequestRoom(ctx context.Context, in *RequestRoomMessage, opts ...grpc.CallOption) (*RoomResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RoomResponse)
	err := c.cc.Invoke(ctx, MatchMaking_RequestRoom_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *matchMakingClient) StartStreamMsg(ctx context.Context, in *StartStreamingMessage, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GameEndedEventMsg], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MatchMaking_ServiceDesc.Streams[0], MatchMaking_StartStreamMsg_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StartStreamingMessage, GameEndedEventMsg]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MatchMaking_StartStreamMsgClient = grpc.ServerStreamingClient[GameEndedEventMsg]

// MatchMakingServer is the server API for MatchMaking service.
// All implementations must embed UnimplementedMatchMakingServer
// for forward compatibility.
type MatchMakingServer interface {
	RequestRoom(context.Context, *RequestRoomMessage) (*RoomResponse, error)
	StartStreamMsg(*StartStreamingMessage, grpc.ServerStreamingServer[GameEndedEventMsg]) error
	mustEmbedUnimplementedMatchMakingServer()
}

// UnimplementedMatchMakingServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMatchMakingServer struct{}

func (UnimplementedMatchMakingServer) RequestRoom(context.Context, *RequestRoomMessage) (*RoomResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestRoom not implemented")
}
func (UnimplementedMatchMakingServer) StartStreamMsg(*StartStreamingMessage, grpc.ServerStreamingServer[GameEndedEventMsg]) error {
	return status.Errorf(codes.Unimplemented, "method StartStreamMsg not implemented")
}
func (UnimplementedMatchMakingServer) mustEmbedUnimplementedMatchMakingServer() {}
func (UnimplementedMatchMakingServer) testEmbeddedByValue()                     {}

// UnsafeMatchMakingServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MatchMakingServer will
// result in compilation errors.
type UnsafeMatchMakingServer interface {
	mustEmbedUnimplementedMatchMakingServer()
}

func RegisterMatchMakingServer(s grpc.ServiceRegistrar, srv MatchMakingServer) {
	// If the following call pancis, it indicates UnimplementedMatchMakingServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MatchMaking_ServiceDesc, srv)
}

func _MatchMaking_RequestRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestRoomMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchMakingServer).RequestRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MatchMaking_RequestRoom_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchMakingServer).RequestRoom(ctx, req.(*RequestRoomMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _MatchMaking_StartStreamMsg_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StartStreamingMessage)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MatchMakingServer).StartStreamMsg(m, &grpc.GenericServerStream[StartStreamingMessage, GameEndedEventMsg]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MatchMaking_StartStreamMsgServer = grpc.ServerStreamingServer[GameEndedEventMsg]

// MatchMaking_ServiceDesc is the grpc.ServiceDesc for MatchMaking service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MatchMaking_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "MatchMaking",
	HandlerType: (*MatchMakingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestRoom",
			Handler:    _MatchMaking_RequestRoom_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StartStreamMsg",
			Handler:       _MatchMaking_StartStreamMsg_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "matchmaking_grpc.proto",
}
