// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: proto/game_server.proto

package grpc_server

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestRoomMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId_1    string                 `protobuf:"bytes,1,opt,name=client_id_1,json=clientId1,proto3" json:"client_id_1,omitempty"`
	ClientId_2    string                 `protobuf:"bytes,2,opt,name=client_id_2,json=clientId2,proto3" json:"client_id_2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestRoomMessage) Reset() {
	*x = RequestRoomMessage{}
	mi := &file_proto_game_server_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestRoomMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestRoomMessage) ProtoMessage() {}

func (x *RequestRoomMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_server_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestRoomMessage.ProtoReflect.Descriptor instead.
func (*RequestRoomMessage) Descriptor() ([]byte, []int) {
	return file_proto_game_server_proto_rawDescGZIP(), []int{0}
}

func (x *RequestRoomMessage) GetClientId_1() string {
	if x != nil {
		return x.ClientId_1
	}
	return ""
}

func (x *RequestRoomMessage) GetClientId_2() string {
	if x != nil {
		return x.ClientId_2
	}
	return ""
}

type Room struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Room) Reset() {
	*x = Room{}
	mi := &file_proto_game_server_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Room) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Room) ProtoMessage() {}

func (x *Room) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_server_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Room.ProtoReflect.Descriptor instead.
func (*Room) Descriptor() ([]byte, []int) {
	return file_proto_game_server_proto_rawDescGZIP(), []int{1}
}

func (x *Room) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

var File_proto_game_server_proto protoreflect.FileDescriptor

const file_proto_game_server_proto_rawDesc = "" +
	"\n" +
	"\x17proto/game_server.proto\"T\n" +
	"\x12RequestRoomMessage\x12\x1e\n" +
	"\vclient_id_1\x18\x01 \x01(\tR\tclientId1\x12\x1e\n" +
	"\vclient_id_2\x18\x02 \x01(\tR\tclientId2\"\x1f\n" +
	"\x04Room\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId29\n" +
	"\n" +
	"GameServer\x12+\n" +
	"\vRequestRoom\x12\x13.RequestRoomMessage\x1a\x05.Room\"\x00B\bZ\x06.;echob\x06proto3"

var (
	file_proto_game_server_proto_rawDescOnce sync.Once
	file_proto_game_server_proto_rawDescData []byte
)

func file_proto_game_server_proto_rawDescGZIP() []byte {
	file_proto_game_server_proto_rawDescOnce.Do(func() {
		file_proto_game_server_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_game_server_proto_rawDesc), len(file_proto_game_server_proto_rawDesc)))
	})
	return file_proto_game_server_proto_rawDescData
}

var file_proto_game_server_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_game_server_proto_goTypes = []any{
	(*RequestRoomMessage)(nil), // 0: RequestRoomMessage
	(*Room)(nil),               // 1: Room
}
var file_proto_game_server_proto_depIdxs = []int32{
	0, // 0: GameServer.RequestRoom:input_type -> RequestRoomMessage
	1, // 1: GameServer.RequestRoom:output_type -> Room
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_game_server_proto_init() }
func file_proto_game_server_proto_init() {
	if File_proto_game_server_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_game_server_proto_rawDesc), len(file_proto_game_server_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_game_server_proto_goTypes,
		DependencyIndexes: file_proto_game_server_proto_depIdxs,
		MessageInfos:      file_proto_game_server_proto_msgTypes,
	}.Build()
	File_proto_game_server_proto = out.File
	file_proto_game_server_proto_goTypes = nil
	file_proto_game_server_proto_depIdxs = nil
}
