// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: auth_grpc.proto

package auth_grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Result struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Code          int32                  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Result) Reset() {
	*x = Result{}
	mi := &file_auth_grpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_auth_grpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_auth_grpc_proto_rawDescGZIP(), []int{0}
}

func (x *Result) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *Result) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Result) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Session struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Username      string                 `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	Issued        *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=issued,proto3" json:"issued,omitempty"`
	Expires       *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=expires,proto3" json:"expires,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Session) Reset() {
	*x = Session{}
	mi := &file_auth_grpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_auth_grpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_auth_grpc_proto_rawDescGZIP(), []int{1}
}

func (x *Session) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *Session) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Session) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Session) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Session) GetIssued() *timestamppb.Timestamp {
	if x != nil {
		return x.Issued
	}
	return nil
}

func (x *Session) GetExpires() *timestamppb.Timestamp {
	if x != nil {
		return x.Expires
	}
	return nil
}

type UserLoggedIn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Res           *Result                `protobuf:"bytes,1,opt,name=res,proto3" json:"res,omitempty"`
	Session       *Session               `protobuf:"bytes,2,opt,name=session,proto3,oneof" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserLoggedIn) Reset() {
	*x = UserLoggedIn{}
	mi := &file_auth_grpc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserLoggedIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserLoggedIn) ProtoMessage() {}

func (x *UserLoggedIn) ProtoReflect() protoreflect.Message {
	mi := &file_auth_grpc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserLoggedIn.ProtoReflect.Descriptor instead.
func (*UserLoggedIn) Descriptor() ([]byte, []int) {
	return file_auth_grpc_proto_rawDescGZIP(), []int{2}
}

func (x *UserLoggedIn) GetRes() *Result {
	if x != nil {
		return x.Res
	}
	return nil
}

func (x *UserLoggedIn) GetSession() *Session {
	if x != nil {
		return x.Session
	}
	return nil
}

type LoginInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OriginIp      string                 `protobuf:"bytes,1,opt,name=origin_ip,json=originIp,proto3" json:"origin_ip,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginInput) Reset() {
	*x = LoginInput{}
	mi := &file_auth_grpc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginInput) ProtoMessage() {}

func (x *LoginInput) ProtoReflect() protoreflect.Message {
	mi := &file_auth_grpc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginInput.ProtoReflect.Descriptor instead.
func (*LoginInput) Descriptor() ([]byte, []int) {
	return file_auth_grpc_proto_rawDescGZIP(), []int{3}
}

func (x *LoginInput) GetOriginIp() string {
	if x != nil {
		return x.OriginIp
	}
	return ""
}

func (x *LoginInput) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginInput) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type EmailVerificationInput struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	OriginIp          string                 `protobuf:"bytes,1,opt,name=origin_ip,json=originIp,proto3" json:"origin_ip,omitempty"`
	VerificationToken string                 `protobuf:"bytes,2,opt,name=verification_token,json=verificationToken,proto3" json:"verification_token,omitempty"`
	VerificationCode  string                 `protobuf:"bytes,3,opt,name=verification_code,json=verificationCode,proto3" json:"verification_code,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *EmailVerificationInput) Reset() {
	*x = EmailVerificationInput{}
	mi := &file_auth_grpc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmailVerificationInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailVerificationInput) ProtoMessage() {}

func (x *EmailVerificationInput) ProtoReflect() protoreflect.Message {
	mi := &file_auth_grpc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailVerificationInput.ProtoReflect.Descriptor instead.
func (*EmailVerificationInput) Descriptor() ([]byte, []int) {
	return file_auth_grpc_proto_rawDescGZIP(), []int{4}
}

func (x *EmailVerificationInput) GetOriginIp() string {
	if x != nil {
		return x.OriginIp
	}
	return ""
}

func (x *EmailVerificationInput) GetVerificationToken() string {
	if x != nil {
		return x.VerificationToken
	}
	return ""
}

func (x *EmailVerificationInput) GetVerificationCode() string {
	if x != nil {
		return x.VerificationCode
	}
	return ""
}

type EmailVerificationPending struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Res               *Result                `protobuf:"bytes,1,opt,name=res,proto3" json:"res,omitempty"`
	VerificationToken *string                `protobuf:"bytes,2,opt,name=verification_token,json=verificationToken,proto3,oneof" json:"verification_token,omitempty"`
	Email             *string                `protobuf:"bytes,3,opt,name=email,proto3,oneof" json:"email,omitempty"`
	VerificationType  *string                `protobuf:"bytes,4,opt,name=verification_type,json=verificationType,proto3,oneof" json:"verification_type,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *EmailVerificationPending) Reset() {
	*x = EmailVerificationPending{}
	mi := &file_auth_grpc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmailVerificationPending) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailVerificationPending) ProtoMessage() {}

func (x *EmailVerificationPending) ProtoReflect() protoreflect.Message {
	mi := &file_auth_grpc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailVerificationPending.ProtoReflect.Descriptor instead.
func (*EmailVerificationPending) Descriptor() ([]byte, []int) {
	return file_auth_grpc_proto_rawDescGZIP(), []int{5}
}

func (x *EmailVerificationPending) GetRes() *Result {
	if x != nil {
		return x.Res
	}
	return nil
}

func (x *EmailVerificationPending) GetVerificationToken() string {
	if x != nil && x.VerificationToken != nil {
		return *x.VerificationToken
	}
	return ""
}

func (x *EmailVerificationPending) GetEmail() string {
	if x != nil && x.Email != nil {
		return *x.Email
	}
	return ""
}

func (x *EmailVerificationPending) GetVerificationType() string {
	if x != nil && x.VerificationType != nil {
		return *x.VerificationType
	}
	return ""
}

type StartRegistrationInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OriginIp      string                 `protobuf:"bytes,1,opt,name=origin_ip,json=originIp,proto3" json:"origin_ip,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartRegistrationInput) Reset() {
	*x = StartRegistrationInput{}
	mi := &file_auth_grpc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartRegistrationInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRegistrationInput) ProtoMessage() {}

func (x *StartRegistrationInput) ProtoReflect() protoreflect.Message {
	mi := &file_auth_grpc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRegistrationInput.ProtoReflect.Descriptor instead.
func (*StartRegistrationInput) Descriptor() ([]byte, []int) {
	return file_auth_grpc_proto_rawDescGZIP(), []int{6}
}

func (x *StartRegistrationInput) GetOriginIp() string {
	if x != nil {
		return x.OriginIp
	}
	return ""
}

func (x *StartRegistrationInput) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *StartRegistrationInput) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *StartRegistrationInput) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type StartPasswordChangeInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OriginIp      string                 `protobuf:"bytes,1,opt,name=origin_ip,json=originIp,proto3" json:"origin_ip,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartPasswordChangeInput) Reset() {
	*x = StartPasswordChangeInput{}
	mi := &file_auth_grpc_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartPasswordChangeInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartPasswordChangeInput) ProtoMessage() {}

func (x *StartPasswordChangeInput) ProtoReflect() protoreflect.Message {
	mi := &file_auth_grpc_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartPasswordChangeInput.ProtoReflect.Descriptor instead.
func (*StartPasswordChangeInput) Descriptor() ([]byte, []int) {
	return file_auth_grpc_proto_rawDescGZIP(), []int{7}
}

func (x *StartPasswordChangeInput) GetOriginIp() string {
	if x != nil {
		return x.OriginIp
	}
	return ""
}

func (x *StartPasswordChangeInput) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type PasswordChangeRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Res                 *Result                `protobuf:"bytes,1,opt,name=res,proto3" json:"res,omitempty"`
	PasswordChangeToken *string                `protobuf:"bytes,2,opt,name=password_change_token,json=passwordChangeToken,proto3,oneof" json:"password_change_token,omitempty"`
	PasswordChangeCode  *string                `protobuf:"bytes,3,opt,name=password_change_code,json=passwordChangeCode,proto3,oneof" json:"password_change_code,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *PasswordChangeRequest) Reset() {
	*x = PasswordChangeRequest{}
	mi := &file_auth_grpc_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PasswordChangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PasswordChangeRequest) ProtoMessage() {}

func (x *PasswordChangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_grpc_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PasswordChangeRequest.ProtoReflect.Descriptor instead.
func (*PasswordChangeRequest) Descriptor() ([]byte, []int) {
	return file_auth_grpc_proto_rawDescGZIP(), []int{8}
}

func (x *PasswordChangeRequest) GetRes() *Result {
	if x != nil {
		return x.Res
	}
	return nil
}

func (x *PasswordChangeRequest) GetPasswordChangeToken() string {
	if x != nil && x.PasswordChangeToken != nil {
		return *x.PasswordChangeToken
	}
	return ""
}

func (x *PasswordChangeRequest) GetPasswordChangeCode() string {
	if x != nil && x.PasswordChangeCode != nil {
		return *x.PasswordChangeCode
	}
	return ""
}

type PasswordChangeInput struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	OriginIp            string                 `protobuf:"bytes,1,opt,name=origin_ip,json=originIp,proto3" json:"origin_ip,omitempty"`
	NewPassword         string                 `protobuf:"bytes,2,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	PasswordChangeToken string                 `protobuf:"bytes,3,opt,name=password_change_token,json=passwordChangeToken,proto3" json:"password_change_token,omitempty"`
	PasswordChangeCode  string                 `protobuf:"bytes,4,opt,name=password_change_code,json=passwordChangeCode,proto3" json:"password_change_code,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *PasswordChangeInput) Reset() {
	*x = PasswordChangeInput{}
	mi := &file_auth_grpc_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PasswordChangeInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PasswordChangeInput) ProtoMessage() {}

func (x *PasswordChangeInput) ProtoReflect() protoreflect.Message {
	mi := &file_auth_grpc_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PasswordChangeInput.ProtoReflect.Descriptor instead.
func (*PasswordChangeInput) Descriptor() ([]byte, []int) {
	return file_auth_grpc_proto_rawDescGZIP(), []int{9}
}

func (x *PasswordChangeInput) GetOriginIp() string {
	if x != nil {
		return x.OriginIp
	}
	return ""
}

func (x *PasswordChangeInput) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

func (x *PasswordChangeInput) GetPasswordChangeToken() string {
	if x != nil {
		return x.PasswordChangeToken
	}
	return ""
}

func (x *PasswordChangeInput) GetPasswordChangeCode() string {
	if x != nil {
		return x.PasswordChangeCode
	}
	return ""
}

type StartEmailChangeInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OriginIp      string                 `protobuf:"bytes,1,opt,name=origin_ip,json=originIp,proto3" json:"origin_ip,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartEmailChangeInput) Reset() {
	*x = StartEmailChangeInput{}
	mi := &file_auth_grpc_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartEmailChangeInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartEmailChangeInput) ProtoMessage() {}

func (x *StartEmailChangeInput) ProtoReflect() protoreflect.Message {
	mi := &file_auth_grpc_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartEmailChangeInput.ProtoReflect.Descriptor instead.
func (*StartEmailChangeInput) Descriptor() ([]byte, []int) {
	return file_auth_grpc_proto_rawDescGZIP(), []int{10}
}

func (x *StartEmailChangeInput) GetOriginIp() string {
	if x != nil {
		return x.OriginIp
	}
	return ""
}

func (x *StartEmailChangeInput) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type EmailChangeRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Res              *Result                `protobuf:"bytes,1,opt,name=res,proto3" json:"res,omitempty"`
	EmailChangeToken *string                `protobuf:"bytes,2,opt,name=email_change_token,json=emailChangeToken,proto3,oneof" json:"email_change_token,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *EmailChangeRequest) Reset() {
	*x = EmailChangeRequest{}
	mi := &file_auth_grpc_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmailChangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailChangeRequest) ProtoMessage() {}

func (x *EmailChangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_grpc_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailChangeRequest.ProtoReflect.Descriptor instead.
func (*EmailChangeRequest) Descriptor() ([]byte, []int) {
	return file_auth_grpc_proto_rawDescGZIP(), []int{11}
}

func (x *EmailChangeRequest) GetRes() *Result {
	if x != nil {
		return x.Res
	}
	return nil
}

func (x *EmailChangeRequest) GetEmailChangeToken() string {
	if x != nil && x.EmailChangeToken != nil {
		return *x.EmailChangeToken
	}
	return ""
}

type ChangeEmailInput struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	OriginIp         string                 `protobuf:"bytes,1,opt,name=origin_ip,json=originIp,proto3" json:"origin_ip,omitempty"`
	EmailChangeToken string                 `protobuf:"bytes,2,opt,name=email_change_token,json=emailChangeToken,proto3" json:"email_change_token,omitempty"`
	NewEmail         string                 `protobuf:"bytes,3,opt,name=new_email,json=newEmail,proto3" json:"new_email,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ChangeEmailInput) Reset() {
	*x = ChangeEmailInput{}
	mi := &file_auth_grpc_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeEmailInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeEmailInput) ProtoMessage() {}

func (x *ChangeEmailInput) ProtoReflect() protoreflect.Message {
	mi := &file_auth_grpc_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeEmailInput.ProtoReflect.Descriptor instead.
func (*ChangeEmailInput) Descriptor() ([]byte, []int) {
	return file_auth_grpc_proto_rawDescGZIP(), []int{12}
}

func (x *ChangeEmailInput) GetOriginIp() string {
	if x != nil {
		return x.OriginIp
	}
	return ""
}

func (x *ChangeEmailInput) GetEmailChangeToken() string {
	if x != nil {
		return x.EmailChangeToken
	}
	return ""
}

func (x *ChangeEmailInput) GetNewEmail() string {
	if x != nil {
		return x.NewEmail
	}
	return ""
}

var File_auth_grpc_proto protoreflect.FileDescriptor

const file_auth_grpc_proto_rawDesc = "" +
	"\n" +
	"\x0fauth_grpc.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"F\n" +
	"\x06Result\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\xd4\x01\n" +
	"\aSession\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1a\n" +
	"\busername\x18\x04 \x01(\tR\busername\x122\n" +
	"\x06issued\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x06issued\x124\n" +
	"\aexpires\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\aexpires\"^\n" +
	"\fUserLoggedIn\x12\x19\n" +
	"\x03res\x18\x01 \x01(\v2\a.ResultR\x03res\x12'\n" +
	"\asession\x18\x02 \x01(\v2\b.SessionH\x00R\asession\x88\x01\x01B\n" +
	"\n" +
	"\b_session\"[\n" +
	"\n" +
	"LoginInput\x12\x1b\n" +
	"\torigin_ip\x18\x01 \x01(\tR\boriginIp\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\"\x91\x01\n" +
	"\x16EmailVerificationInput\x12\x1b\n" +
	"\torigin_ip\x18\x01 \x01(\tR\boriginIp\x12-\n" +
	"\x12verification_token\x18\x02 \x01(\tR\x11verificationToken\x12+\n" +
	"\x11verification_code\x18\x03 \x01(\tR\x10verificationCode\"\xed\x01\n" +
	"\x18EmailVerificationPending\x12\x19\n" +
	"\x03res\x18\x01 \x01(\v2\a.ResultR\x03res\x122\n" +
	"\x12verification_token\x18\x02 \x01(\tH\x00R\x11verificationToken\x88\x01\x01\x12\x19\n" +
	"\x05email\x18\x03 \x01(\tH\x01R\x05email\x88\x01\x01\x120\n" +
	"\x11verification_type\x18\x04 \x01(\tH\x02R\x10verificationType\x88\x01\x01B\x15\n" +
	"\x13_verification_tokenB\b\n" +
	"\x06_emailB\x14\n" +
	"\x12_verification_type\"\x83\x01\n" +
	"\x16StartRegistrationInput\x12\x1b\n" +
	"\torigin_ip\x18\x01 \x01(\tR\boriginIp\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\"M\n" +
	"\x18StartPasswordChangeInput\x12\x1b\n" +
	"\torigin_ip\x18\x01 \x01(\tR\boriginIp\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\"\xd5\x01\n" +
	"\x15PasswordChangeRequest\x12\x19\n" +
	"\x03res\x18\x01 \x01(\v2\a.ResultR\x03res\x127\n" +
	"\x15password_change_token\x18\x02 \x01(\tH\x00R\x13passwordChangeToken\x88\x01\x01\x125\n" +
	"\x14password_change_code\x18\x03 \x01(\tH\x01R\x12passwordChangeCode\x88\x01\x01B\x18\n" +
	"\x16_password_change_tokenB\x17\n" +
	"\x15_password_change_code\"\xbb\x01\n" +
	"\x13PasswordChangeInput\x12\x1b\n" +
	"\torigin_ip\x18\x01 \x01(\tR\boriginIp\x12!\n" +
	"\fnew_password\x18\x02 \x01(\tR\vnewPassword\x122\n" +
	"\x15password_change_token\x18\x03 \x01(\tR\x13passwordChangeToken\x120\n" +
	"\x14password_change_code\x18\x04 \x01(\tR\x12passwordChangeCode\"J\n" +
	"\x15StartEmailChangeInput\x12\x1b\n" +
	"\torigin_ip\x18\x01 \x01(\tR\boriginIp\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\"y\n" +
	"\x12EmailChangeRequest\x12\x19\n" +
	"\x03res\x18\x01 \x01(\v2\a.ResultR\x03res\x121\n" +
	"\x12email_change_token\x18\x02 \x01(\tH\x00R\x10emailChangeToken\x88\x01\x01B\x15\n" +
	"\x13_email_change_token\"z\n" +
	"\x10ChangeEmailInput\x12\x1b\n" +
	"\torigin_ip\x18\x01 \x01(\tR\boriginIp\x12,\n" +
	"\x12email_change_token\x18\x02 \x01(\tR\x10emailChangeToken\x12\x1b\n" +
	"\tnew_email\x18\x03 \x01(\tR\bnewEmail2\x96\x05\n" +
	"\x04Auth\x12#\n" +
	"\x05Login\x12\v.LoginInput\x1a\r.UserLoggedIn\x12G\n" +
	"\x11StartRegistration\x12\x17.StartRegistrationInput\x1a\x19.EmailVerificationPending\x12=\n" +
	"\x13ConfirmRegistration\x12\x17.EmailVerificationInput\x1a\r.UserLoggedIn\x12K\n" +
	"\x13StartPasswordChange\x12\x19.StartPasswordChangeInput\x1a\x19.EmailVerificationPending\x12L\n" +
	"\x19PasswordChangeVerifyEmail\x12\x17.EmailVerificationInput\x1a\x16.PasswordChangeRequest\x125\n" +
	"\x0eChangePassword\x12\x14.PasswordChangeInput\x1a\r.UserLoggedIn\x12E\n" +
	"\x10StartEmailChange\x12\x16.StartEmailChangeInput\x1a\x19.EmailVerificationPending\x12M\n" +
	"\x1dEmailChangeVerifyCurrentEmail\x12\x17.EmailVerificationInput\x1a\x13.EmailChangeRequest\x12;\n" +
	"\vChangeEmail\x12\x11.ChangeEmailInput\x1a\x19.EmailVerificationPending\x12<\n" +
	"\x12ConfirmEmailChange\x12\x17.EmailVerificationInput\x1a\r.UserLoggedInB\rZ\v./auth_grpcb\x06proto3"

var (
	file_auth_grpc_proto_rawDescOnce sync.Once
	file_auth_grpc_proto_rawDescData []byte
)

func file_auth_grpc_proto_rawDescGZIP() []byte {
	file_auth_grpc_proto_rawDescOnce.Do(func() {
		file_auth_grpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_grpc_proto_rawDesc), len(file_auth_grpc_proto_rawDesc)))
	})
	return file_auth_grpc_proto_rawDescData
}

var file_auth_grpc_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_auth_grpc_proto_goTypes = []any{
	(*Result)(nil),                   // 0: Result
	(*Session)(nil),                  // 1: Session
	(*UserLoggedIn)(nil),             // 2: UserLoggedIn
	(*LoginInput)(nil),               // 3: LoginInput
	(*EmailVerificationInput)(nil),   // 4: EmailVerificationInput
	(*EmailVerificationPending)(nil), // 5: EmailVerificationPending
	(*StartRegistrationInput)(nil),   // 6: StartRegistrationInput
	(*StartPasswordChangeInput)(nil), // 7: StartPasswordChangeInput
	(*PasswordChangeRequest)(nil),    // 8: PasswordChangeRequest
	(*PasswordChangeInput)(nil),      // 9: PasswordChangeInput
	(*StartEmailChangeInput)(nil),    // 10: StartEmailChangeInput
	(*EmailChangeRequest)(nil),       // 11: EmailChangeRequest
	(*ChangeEmailInput)(nil),         // 12: ChangeEmailInput
	(*timestamppb.Timestamp)(nil),    // 13: google.protobuf.Timestamp
}
var file_auth_grpc_proto_depIdxs = []int32{
	13, // 0: Session.issued:type_name -> google.protobuf.Timestamp
	13, // 1: Session.expires:type_name -> google.protobuf.Timestamp
	0,  // 2: UserLoggedIn.res:type_name -> Result
	1,  // 3: UserLoggedIn.session:type_name -> Session
	0,  // 4: EmailVerificationPending.res:type_name -> Result
	0,  // 5: PasswordChangeRequest.res:type_name -> Result
	0,  // 6: EmailChangeRequest.res:type_name -> Result
	3,  // 7: Auth.Login:input_type -> LoginInput
	6,  // 8: Auth.StartRegistration:input_type -> StartRegistrationInput
	4,  // 9: Auth.ConfirmRegistration:input_type -> EmailVerificationInput
	7,  // 10: Auth.StartPasswordChange:input_type -> StartPasswordChangeInput
	4,  // 11: Auth.PasswordChangeVerifyEmail:input_type -> EmailVerificationInput
	9,  // 12: Auth.ChangePassword:input_type -> PasswordChangeInput
	10, // 13: Auth.StartEmailChange:input_type -> StartEmailChangeInput
	4,  // 14: Auth.EmailChangeVerifyCurrentEmail:input_type -> EmailVerificationInput
	12, // 15: Auth.ChangeEmail:input_type -> ChangeEmailInput
	4,  // 16: Auth.ConfirmEmailChange:input_type -> EmailVerificationInput
	2,  // 17: Auth.Login:output_type -> UserLoggedIn
	5,  // 18: Auth.StartRegistration:output_type -> EmailVerificationPending
	2,  // 19: Auth.ConfirmRegistration:output_type -> UserLoggedIn
	5,  // 20: Auth.StartPasswordChange:output_type -> EmailVerificationPending
	8,  // 21: Auth.PasswordChangeVerifyEmail:output_type -> PasswordChangeRequest
	2,  // 22: Auth.ChangePassword:output_type -> UserLoggedIn
	5,  // 23: Auth.StartEmailChange:output_type -> EmailVerificationPending
	11, // 24: Auth.EmailChangeVerifyCurrentEmail:output_type -> EmailChangeRequest
	5,  // 25: Auth.ChangeEmail:output_type -> EmailVerificationPending
	2,  // 26: Auth.ConfirmEmailChange:output_type -> UserLoggedIn
	17, // [17:27] is the sub-list for method output_type
	7,  // [7:17] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_auth_grpc_proto_init() }
func file_auth_grpc_proto_init() {
	if File_auth_grpc_proto != nil {
		return
	}
	file_auth_grpc_proto_msgTypes[2].OneofWrappers = []any{}
	file_auth_grpc_proto_msgTypes[5].OneofWrappers = []any{}
	file_auth_grpc_proto_msgTypes[8].OneofWrappers = []any{}
	file_auth_grpc_proto_msgTypes[11].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_grpc_proto_rawDesc), len(file_auth_grpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auth_grpc_proto_goTypes,
		DependencyIndexes: file_auth_grpc_proto_depIdxs,
		MessageInfos:      file_auth_grpc_proto_msgTypes,
	}.Build()
	File_auth_grpc_proto = out.File
	file_auth_grpc_proto_goTypes = nil
	file_auth_grpc_proto_depIdxs = nil
}
