// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: auth_grpc.proto

package auth_grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Auth_Login_FullMethodName                         = "/Auth/Login"
	Auth_StartRegistration_FullMethodName             = "/Auth/StartRegistration"
	Auth_ConfirmRegistration_FullMethodName           = "/Auth/ConfirmRegistration"
	Auth_StartPasswordChange_FullMethodName           = "/Auth/StartPasswordChange"
	Auth_PasswordChangeVerifyEmail_FullMethodName     = "/Auth/PasswordChangeVerifyEmail"
	Auth_ChangePassword_FullMethodName                = "/Auth/ChangePassword"
	Auth_StartEmailChange_FullMethodName              = "/Auth/StartEmailChange"
	Auth_EmailChangeVerifyCurrentEmail_FullMethodName = "/Auth/EmailChangeVerifyCurrentEmail"
	Auth_ChangeEmail_FullMethodName                   = "/Auth/ChangeEmail"
	Auth_ConfirmEmailChange_FullMethodName            = "/Auth/ConfirmEmailChange"
	Auth_ValidateSession_FullMethodName               = "/Auth/ValidateSession"
)

// AuthClient is the client API for Auth service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuthClient interface {
	// Authentication
	Login(ctx context.Context, in *LoginInput, opts ...grpc.CallOption) (*UserLoggedIn, error)
	// Registration flow
	StartRegistration(ctx context.Context, in *StartRegistrationInput, opts ...grpc.CallOption) (*EmailVerificationPending, error)
	ConfirmRegistration(ctx context.Context, in *EmailVerificationInput, opts ...grpc.CallOption) (*UserLoggedIn, error)
	// Password change flow
	StartPasswordChange(ctx context.Context, in *StartPasswordChangeInput, opts ...grpc.CallOption) (*EmailVerificationPending, error)
	PasswordChangeVerifyEmail(ctx context.Context, in *EmailVerificationInput, opts ...grpc.CallOption) (*PasswordChangeRequest, error)
	ChangePassword(ctx context.Context, in *PasswordChangeInput, opts ...grpc.CallOption) (*UserLoggedIn, error)
	// Email change flow
	StartEmailChange(ctx context.Context, in *StartEmailChangeInput, opts ...grpc.CallOption) (*EmailVerificationPending, error)
	EmailChangeVerifyCurrentEmail(ctx context.Context, in *EmailVerificationInput, opts ...grpc.CallOption) (*EmailChangeRequest, error)
	ChangeEmail(ctx context.Context, in *ChangeEmailInput, opts ...grpc.CallOption) (*EmailVerificationPending, error)
	ConfirmEmailChange(ctx context.Context, in *EmailVerificationInput, opts ...grpc.CallOption) (*UserLoggedIn, error)
	// Validate session
	ValidateSession(ctx context.Context, in *SessionValidationInput, opts ...grpc.CallOption) (*UserLoggedIn, error)
}

type authClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthClient(cc grpc.ClientConnInterface) AuthClient {
	return &authClient{cc}
}

func (c *authClient) Login(ctx context.Context, in *LoginInput, opts ...grpc.CallOption) (*UserLoggedIn, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserLoggedIn)
	err := c.cc.Invoke(ctx, Auth_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) StartRegistration(ctx context.Context, in *StartRegistrationInput, opts ...grpc.CallOption) (*EmailVerificationPending, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmailVerificationPending)
	err := c.cc.Invoke(ctx, Auth_StartRegistration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) ConfirmRegistration(ctx context.Context, in *EmailVerificationInput, opts ...grpc.CallOption) (*UserLoggedIn, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserLoggedIn)
	err := c.cc.Invoke(ctx, Auth_ConfirmRegistration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) StartPasswordChange(ctx context.Context, in *StartPasswordChangeInput, opts ...grpc.CallOption) (*EmailVerificationPending, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmailVerificationPending)
	err := c.cc.Invoke(ctx, Auth_StartPasswordChange_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) PasswordChangeVerifyEmail(ctx context.Context, in *EmailVerificationInput, opts ...grpc.CallOption) (*PasswordChangeRequest, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PasswordChangeRequest)
	err := c.cc.Invoke(ctx, Auth_PasswordChangeVerifyEmail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) ChangePassword(ctx context.Context, in *PasswordChangeInput, opts ...grpc.CallOption) (*UserLoggedIn, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserLoggedIn)
	err := c.cc.Invoke(ctx, Auth_ChangePassword_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) StartEmailChange(ctx context.Context, in *StartEmailChangeInput, opts ...grpc.CallOption) (*EmailVerificationPending, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmailVerificationPending)
	err := c.cc.Invoke(ctx, Auth_StartEmailChange_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) EmailChangeVerifyCurrentEmail(ctx context.Context, in *EmailVerificationInput, opts ...grpc.CallOption) (*EmailChangeRequest, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmailChangeRequest)
	err := c.cc.Invoke(ctx, Auth_EmailChangeVerifyCurrentEmail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) ChangeEmail(ctx context.Context, in *ChangeEmailInput, opts ...grpc.CallOption) (*EmailVerificationPending, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmailVerificationPending)
	err := c.cc.Invoke(ctx, Auth_ChangeEmail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) ConfirmEmailChange(ctx context.Context, in *EmailVerificationInput, opts ...grpc.CallOption) (*UserLoggedIn, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserLoggedIn)
	err := c.cc.Invoke(ctx, Auth_ConfirmEmailChange_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) ValidateSession(ctx context.Context, in *SessionValidationInput, opts ...grpc.CallOption) (*UserLoggedIn, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserLoggedIn)
	err := c.cc.Invoke(ctx, Auth_ValidateSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServer is the server API for Auth service.
// All implementations must embed UnimplementedAuthServer
// for forward compatibility.
type AuthServer interface {
	// Authentication
	Login(context.Context, *LoginInput) (*UserLoggedIn, error)
	// Registration flow
	StartRegistration(context.Context, *StartRegistrationInput) (*EmailVerificationPending, error)
	ConfirmRegistration(context.Context, *EmailVerificationInput) (*UserLoggedIn, error)
	// Password change flow
	StartPasswordChange(context.Context, *StartPasswordChangeInput) (*EmailVerificationPending, error)
	PasswordChangeVerifyEmail(context.Context, *EmailVerificationInput) (*PasswordChangeRequest, error)
	ChangePassword(context.Context, *PasswordChangeInput) (*UserLoggedIn, error)
	// Email change flow
	StartEmailChange(context.Context, *StartEmailChangeInput) (*EmailVerificationPending, error)
	EmailChangeVerifyCurrentEmail(context.Context, *EmailVerificationInput) (*EmailChangeRequest, error)
	ChangeEmail(context.Context, *ChangeEmailInput) (*EmailVerificationPending, error)
	ConfirmEmailChange(context.Context, *EmailVerificationInput) (*UserLoggedIn, error)
	// Validate session
	ValidateSession(context.Context, *SessionValidationInput) (*UserLoggedIn, error)
	mustEmbedUnimplementedAuthServer()
}

// UnimplementedAuthServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuthServer struct{}

func (UnimplementedAuthServer) Login(context.Context, *LoginInput) (*UserLoggedIn, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedAuthServer) StartRegistration(context.Context, *StartRegistrationInput) (*EmailVerificationPending, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartRegistration not implemented")
}
func (UnimplementedAuthServer) ConfirmRegistration(context.Context, *EmailVerificationInput) (*UserLoggedIn, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConfirmRegistration not implemented")
}
func (UnimplementedAuthServer) StartPasswordChange(context.Context, *StartPasswordChangeInput) (*EmailVerificationPending, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartPasswordChange not implemented")
}
func (UnimplementedAuthServer) PasswordChangeVerifyEmail(context.Context, *EmailVerificationInput) (*PasswordChangeRequest, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PasswordChangeVerifyEmail not implemented")
}
func (UnimplementedAuthServer) ChangePassword(context.Context, *PasswordChangeInput) (*UserLoggedIn, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangePassword not implemented")
}
func (UnimplementedAuthServer) StartEmailChange(context.Context, *StartEmailChangeInput) (*EmailVerificationPending, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartEmailChange not implemented")
}
func (UnimplementedAuthServer) EmailChangeVerifyCurrentEmail(context.Context, *EmailVerificationInput) (*EmailChangeRequest, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EmailChangeVerifyCurrentEmail not implemented")
}
func (UnimplementedAuthServer) ChangeEmail(context.Context, *ChangeEmailInput) (*EmailVerificationPending, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangeEmail not implemented")
}
func (UnimplementedAuthServer) ConfirmEmailChange(context.Context, *EmailVerificationInput) (*UserLoggedIn, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConfirmEmailChange not implemented")
}
func (UnimplementedAuthServer) ValidateSession(context.Context, *SessionValidationInput) (*UserLoggedIn, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateSession not implemented")
}
func (UnimplementedAuthServer) mustEmbedUnimplementedAuthServer() {}
func (UnimplementedAuthServer) testEmbeddedByValue()              {}

// UnsafeAuthServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthServer will
// result in compilation errors.
type UnsafeAuthServer interface {
	mustEmbedUnimplementedAuthServer()
}

func RegisterAuthServer(s grpc.ServiceRegistrar, srv AuthServer) {
	// If the following call pancis, it indicates UnimplementedAuthServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Auth_ServiceDesc, srv)
}

func _Auth_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Auth_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).Login(ctx, req.(*LoginInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_StartRegistration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartRegistrationInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).StartRegistration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Auth_StartRegistration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).StartRegistration(ctx, req.(*StartRegistrationInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_ConfirmRegistration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmailVerificationInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).ConfirmRegistration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Auth_ConfirmRegistration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).ConfirmRegistration(ctx, req.(*EmailVerificationInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_StartPasswordChange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartPasswordChangeInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).StartPasswordChange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Auth_StartPasswordChange_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).StartPasswordChange(ctx, req.(*StartPasswordChangeInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_PasswordChangeVerifyEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmailVerificationInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).PasswordChangeVerifyEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Auth_PasswordChangeVerifyEmail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).PasswordChangeVerifyEmail(ctx, req.(*EmailVerificationInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_ChangePassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PasswordChangeInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).ChangePassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Auth_ChangePassword_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).ChangePassword(ctx, req.(*PasswordChangeInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_StartEmailChange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartEmailChangeInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).StartEmailChange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Auth_StartEmailChange_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).StartEmailChange(ctx, req.(*StartEmailChangeInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_EmailChangeVerifyCurrentEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmailVerificationInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).EmailChangeVerifyCurrentEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Auth_EmailChangeVerifyCurrentEmail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).EmailChangeVerifyCurrentEmail(ctx, req.(*EmailVerificationInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_ChangeEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeEmailInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).ChangeEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Auth_ChangeEmail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).ChangeEmail(ctx, req.(*ChangeEmailInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_ConfirmEmailChange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmailVerificationInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).ConfirmEmailChange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Auth_ConfirmEmailChange_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).ConfirmEmailChange(ctx, req.(*EmailVerificationInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_ValidateSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionValidationInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).ValidateSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Auth_ValidateSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).ValidateSession(ctx, req.(*SessionValidationInput))
	}
	return interceptor(ctx, in, info, handler)
}

// Auth_ServiceDesc is the grpc.ServiceDesc for Auth service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Auth_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Auth",
	HandlerType: (*AuthServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _Auth_Login_Handler,
		},
		{
			MethodName: "StartRegistration",
			Handler:    _Auth_StartRegistration_Handler,
		},
		{
			MethodName: "ConfirmRegistration",
			Handler:    _Auth_ConfirmRegistration_Handler,
		},
		{
			MethodName: "StartPasswordChange",
			Handler:    _Auth_StartPasswordChange_Handler,
		},
		{
			MethodName: "PasswordChangeVerifyEmail",
			Handler:    _Auth_PasswordChangeVerifyEmail_Handler,
		},
		{
			MethodName: "ChangePassword",
			Handler:    _Auth_ChangePassword_Handler,
		},
		{
			MethodName: "StartEmailChange",
			Handler:    _Auth_StartEmailChange_Handler,
		},
		{
			MethodName: "EmailChangeVerifyCurrentEmail",
			Handler:    _Auth_EmailChangeVerifyCurrentEmail_Handler,
		},
		{
			MethodName: "ChangeEmail",
			Handler:    _Auth_ChangeEmail_Handler,
		},
		{
			MethodName: "ConfirmEmailChange",
			Handler:    _Auth_ConfirmEmailChange_Handler,
		},
		{
			MethodName: "ValidateSession",
			Handler:    _Auth_ValidateSession_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth_grpc.proto",
}
