// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: auth_grpc.proto

package auth_grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClientIdentification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	UserAgent     string                 `protobuf:"bytes,2,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientIdentification) Reset() {
	*x = ClientIdentification{}
	mi := &file_auth_grpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientIdentification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientIdentification) ProtoMessage() {}

func (x *ClientIdentification) ProtoReflect() protoreflect.Message {
	mi := &file_auth_grpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientIdentification.ProtoReflect.Descriptor instead.
func (*ClientIdentification) Descriptor() ([]byte, []int) {
	return file_auth_grpc_proto_rawDescGZIP(), []int{0}
}

func (x *ClientIdentification) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *ClientIdentification) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

type UserData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserData) Reset() {
	*x = UserData{}
	mi := &file_auth_grpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserData) ProtoMessage() {}

func (x *UserData) ProtoReflect() protoreflect.Message {
	mi := &file_auth_grpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserData.ProtoReflect.Descriptor instead.
func (*UserData) Descriptor() ([]byte, []int) {
	return file_auth_grpc_proto_rawDescGZIP(), []int{1}
}

func (x *UserData) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserData) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserData) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type Result struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Result) Reset() {
	*x = Result{}
	mi := &file_auth_grpc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_auth_grpc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_auth_grpc_proto_rawDescGZIP(), []int{2}
}

func (x *Result) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Result) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RegisterAccountRequestMessage struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	ClientIdentification *ClientIdentification  `protobuf:"bytes,1,opt,name=client_identification,json=clientIdentification,proto3" json:"client_identification,omitempty"`
	Username             string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email                string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Password             string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *RegisterAccountRequestMessage) Reset() {
	*x = RegisterAccountRequestMessage{}
	mi := &file_auth_grpc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAccountRequestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAccountRequestMessage) ProtoMessage() {}

func (x *RegisterAccountRequestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_auth_grpc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAccountRequestMessage.ProtoReflect.Descriptor instead.
func (*RegisterAccountRequestMessage) Descriptor() ([]byte, []int) {
	return file_auth_grpc_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterAccountRequestMessage) GetClientIdentification() *ClientIdentification {
	if x != nil {
		return x.ClientIdentification
	}
	return nil
}

func (x *RegisterAccountRequestMessage) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegisterAccountRequestMessage) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterAccountRequestMessage) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type Token struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionToken  string                 `protobuf:"bytes,1,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`
	CsrfToken     string                 `protobuf:"bytes,2,opt,name=csrf_token,json=csrfToken,proto3" json:"csrf_token,omitempty"`
	Expiration    *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=expiration,proto3,oneof" json:"expiration,omitempty"`
	Issued        *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=issued,proto3,oneof" json:"issued,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Token) Reset() {
	*x = Token{}
	mi := &file_auth_grpc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Token) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Token) ProtoMessage() {}

func (x *Token) ProtoReflect() protoreflect.Message {
	mi := &file_auth_grpc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Token.ProtoReflect.Descriptor instead.
func (*Token) Descriptor() ([]byte, []int) {
	return file_auth_grpc_proto_rawDescGZIP(), []int{4}
}

func (x *Token) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

func (x *Token) GetCsrfToken() string {
	if x != nil {
		return x.CsrfToken
	}
	return ""
}

func (x *Token) GetExpiration() *timestamppb.Timestamp {
	if x != nil {
		return x.Expiration
	}
	return nil
}

func (x *Token) GetIssued() *timestamppb.Timestamp {
	if x != nil {
		return x.Issued
	}
	return nil
}

type RegisterAccountResponseMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Res           *Result                `protobuf:"bytes,1,opt,name=res,proto3" json:"res,omitempty"`
	Token         *Token                 `protobuf:"bytes,2,opt,name=token,proto3,oneof" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterAccountResponseMessage) Reset() {
	*x = RegisterAccountResponseMessage{}
	mi := &file_auth_grpc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAccountResponseMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAccountResponseMessage) ProtoMessage() {}

func (x *RegisterAccountResponseMessage) ProtoReflect() protoreflect.Message {
	mi := &file_auth_grpc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAccountResponseMessage.ProtoReflect.Descriptor instead.
func (*RegisterAccountResponseMessage) Descriptor() ([]byte, []int) {
	return file_auth_grpc_proto_rawDescGZIP(), []int{5}
}

func (x *RegisterAccountResponseMessage) GetRes() *Result {
	if x != nil {
		return x.Res
	}
	return nil
}

func (x *RegisterAccountResponseMessage) GetToken() *Token {
	if x != nil {
		return x.Token
	}
	return nil
}

type LoginRequestMessage struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	ClientIdentification *ClientIdentification  `protobuf:"bytes,1,opt,name=client_identification,json=clientIdentification,proto3" json:"client_identification,omitempty"`
	Email                string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password             string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *LoginRequestMessage) Reset() {
	*x = LoginRequestMessage{}
	mi := &file_auth_grpc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequestMessage) ProtoMessage() {}

func (x *LoginRequestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_auth_grpc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequestMessage.ProtoReflect.Descriptor instead.
func (*LoginRequestMessage) Descriptor() ([]byte, []int) {
	return file_auth_grpc_proto_rawDescGZIP(), []int{6}
}

func (x *LoginRequestMessage) GetClientIdentification() *ClientIdentification {
	if x != nil {
		return x.ClientIdentification
	}
	return nil
}

func (x *LoginRequestMessage) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginRequestMessage) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponseMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Res           *Result                `protobuf:"bytes,1,opt,name=res,proto3" json:"res,omitempty"`
	Token         *Token                 `protobuf:"bytes,2,opt,name=token,proto3,oneof" json:"token,omitempty"`
	User          *UserData              `protobuf:"bytes,3,opt,name=user,proto3,oneof" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponseMessage) Reset() {
	*x = LoginResponseMessage{}
	mi := &file_auth_grpc_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponseMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponseMessage) ProtoMessage() {}

func (x *LoginResponseMessage) ProtoReflect() protoreflect.Message {
	mi := &file_auth_grpc_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponseMessage.ProtoReflect.Descriptor instead.
func (*LoginResponseMessage) Descriptor() ([]byte, []int) {
	return file_auth_grpc_proto_rawDescGZIP(), []int{7}
}

func (x *LoginResponseMessage) GetRes() *Result {
	if x != nil {
		return x.Res
	}
	return nil
}

func (x *LoginResponseMessage) GetToken() *Token {
	if x != nil {
		return x.Token
	}
	return nil
}

func (x *LoginResponseMessage) GetUser() *UserData {
	if x != nil {
		return x.User
	}
	return nil
}

type CheckTokenRequestMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         *Token                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckTokenRequestMessage) Reset() {
	*x = CheckTokenRequestMessage{}
	mi := &file_auth_grpc_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckTokenRequestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckTokenRequestMessage) ProtoMessage() {}

func (x *CheckTokenRequestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_auth_grpc_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckTokenRequestMessage.ProtoReflect.Descriptor instead.
func (*CheckTokenRequestMessage) Descriptor() ([]byte, []int) {
	return file_auth_grpc_proto_rawDescGZIP(), []int{8}
}

func (x *CheckTokenRequestMessage) GetToken() *Token {
	if x != nil {
		return x.Token
	}
	return nil
}

type CheckTokenResponseMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	Token         *Token                 `protobuf:"bytes,2,opt,name=token,proto3,oneof" json:"token,omitempty"`
	User          *UserData              `protobuf:"bytes,3,opt,name=user,proto3,oneof" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckTokenResponseMessage) Reset() {
	*x = CheckTokenResponseMessage{}
	mi := &file_auth_grpc_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckTokenResponseMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckTokenResponseMessage) ProtoMessage() {}

func (x *CheckTokenResponseMessage) ProtoReflect() protoreflect.Message {
	mi := &file_auth_grpc_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckTokenResponseMessage.ProtoReflect.Descriptor instead.
func (*CheckTokenResponseMessage) Descriptor() ([]byte, []int) {
	return file_auth_grpc_proto_rawDescGZIP(), []int{9}
}

func (x *CheckTokenResponseMessage) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *CheckTokenResponseMessage) GetToken() *Token {
	if x != nil {
		return x.Token
	}
	return nil
}

func (x *CheckTokenResponseMessage) GetUser() *UserData {
	if x != nil {
		return x.User
	}
	return nil
}

type ConfirmEmailRequestMessage struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	ClientIdentification  *ClientIdentification  `protobuf:"bytes,1,opt,name=client_identification,json=clientIdentification,proto3" json:"client_identification,omitempty"`
	EmailConfirmationCode string                 `protobuf:"bytes,2,opt,name=email_confirmation_code,json=emailConfirmationCode,proto3" json:"email_confirmation_code,omitempty"`
	Data                  *string                `protobuf:"bytes,3,opt,name=data,proto3,oneof" json:"data,omitempty"` // Additional data for custom confirmations
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ConfirmEmailRequestMessage) Reset() {
	*x = ConfirmEmailRequestMessage{}
	mi := &file_auth_grpc_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmEmailRequestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmEmailRequestMessage) ProtoMessage() {}

func (x *ConfirmEmailRequestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_auth_grpc_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmEmailRequestMessage.ProtoReflect.Descriptor instead.
func (*ConfirmEmailRequestMessage) Descriptor() ([]byte, []int) {
	return file_auth_grpc_proto_rawDescGZIP(), []int{10}
}

func (x *ConfirmEmailRequestMessage) GetClientIdentification() *ClientIdentification {
	if x != nil {
		return x.ClientIdentification
	}
	return nil
}

func (x *ConfirmEmailRequestMessage) GetEmailConfirmationCode() string {
	if x != nil {
		return x.EmailConfirmationCode
	}
	return ""
}

func (x *ConfirmEmailRequestMessage) GetData() string {
	if x != nil && x.Data != nil {
		return *x.Data
	}
	return ""
}

type ConfirmEmailResponseMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Res           *Result                `protobuf:"bytes,1,opt,name=res,proto3" json:"res,omitempty"`
	Token         *Token                 `protobuf:"bytes,2,opt,name=token,proto3,oneof" json:"token,omitempty"`
	User          *UserData              `protobuf:"bytes,3,opt,name=user,proto3,oneof" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmEmailResponseMessage) Reset() {
	*x = ConfirmEmailResponseMessage{}
	mi := &file_auth_grpc_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmEmailResponseMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmEmailResponseMessage) ProtoMessage() {}

func (x *ConfirmEmailResponseMessage) ProtoReflect() protoreflect.Message {
	mi := &file_auth_grpc_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmEmailResponseMessage.ProtoReflect.Descriptor instead.
func (*ConfirmEmailResponseMessage) Descriptor() ([]byte, []int) {
	return file_auth_grpc_proto_rawDescGZIP(), []int{11}
}

func (x *ConfirmEmailResponseMessage) GetRes() *Result {
	if x != nil {
		return x.Res
	}
	return nil
}

func (x *ConfirmEmailResponseMessage) GetToken() *Token {
	if x != nil {
		return x.Token
	}
	return nil
}

func (x *ConfirmEmailResponseMessage) GetUser() *UserData {
	if x != nil {
		return x.User
	}
	return nil
}

type ChangeEmailRequestMessage struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	ClientIdentification *ClientIdentification  `protobuf:"bytes,1,opt,name=client_identification,json=clientIdentification,proto3" json:"client_identification,omitempty"`
	NewEmail             string                 `protobuf:"bytes,2,opt,name=new_email,json=newEmail,proto3" json:"new_email,omitempty"`
	Token                *Token                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ChangeEmailRequestMessage) Reset() {
	*x = ChangeEmailRequestMessage{}
	mi := &file_auth_grpc_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeEmailRequestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeEmailRequestMessage) ProtoMessage() {}

func (x *ChangeEmailRequestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_auth_grpc_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeEmailRequestMessage.ProtoReflect.Descriptor instead.
func (*ChangeEmailRequestMessage) Descriptor() ([]byte, []int) {
	return file_auth_grpc_proto_rawDescGZIP(), []int{12}
}

func (x *ChangeEmailRequestMessage) GetClientIdentification() *ClientIdentification {
	if x != nil {
		return x.ClientIdentification
	}
	return nil
}

func (x *ChangeEmailRequestMessage) GetNewEmail() string {
	if x != nil {
		return x.NewEmail
	}
	return ""
}

func (x *ChangeEmailRequestMessage) GetToken() *Token {
	if x != nil {
		return x.Token
	}
	return nil
}

type ChangeEmailResponseMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Res           *Result                `protobuf:"bytes,1,opt,name=res,proto3" json:"res,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeEmailResponseMessage) Reset() {
	*x = ChangeEmailResponseMessage{}
	mi := &file_auth_grpc_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeEmailResponseMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeEmailResponseMessage) ProtoMessage() {}

func (x *ChangeEmailResponseMessage) ProtoReflect() protoreflect.Message {
	mi := &file_auth_grpc_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeEmailResponseMessage.ProtoReflect.Descriptor instead.
func (*ChangeEmailResponseMessage) Descriptor() ([]byte, []int) {
	return file_auth_grpc_proto_rawDescGZIP(), []int{13}
}

func (x *ChangeEmailResponseMessage) GetRes() *Result {
	if x != nil {
		return x.Res
	}
	return nil
}

type ChangePasswordRequestMessage struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	ClientIdentification *ClientIdentification  `protobuf:"bytes,1,opt,name=client_identification,json=clientIdentification,proto3" json:"client_identification,omitempty"`
	Email                string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Token                *Token                 `protobuf:"bytes,3,opt,name=token,proto3,oneof" json:"token,omitempty"` // It's not mandatory for the user to be logged in
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ChangePasswordRequestMessage) Reset() {
	*x = ChangePasswordRequestMessage{}
	mi := &file_auth_grpc_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangePasswordRequestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangePasswordRequestMessage) ProtoMessage() {}

func (x *ChangePasswordRequestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_auth_grpc_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangePasswordRequestMessage.ProtoReflect.Descriptor instead.
func (*ChangePasswordRequestMessage) Descriptor() ([]byte, []int) {
	return file_auth_grpc_proto_rawDescGZIP(), []int{14}
}

func (x *ChangePasswordRequestMessage) GetClientIdentification() *ClientIdentification {
	if x != nil {
		return x.ClientIdentification
	}
	return nil
}

func (x *ChangePasswordRequestMessage) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ChangePasswordRequestMessage) GetToken() *Token {
	if x != nil {
		return x.Token
	}
	return nil
}

type ChangePasswordResponseMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Res           *Result                `protobuf:"bytes,1,opt,name=res,proto3" json:"res,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangePasswordResponseMessage) Reset() {
	*x = ChangePasswordResponseMessage{}
	mi := &file_auth_grpc_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangePasswordResponseMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangePasswordResponseMessage) ProtoMessage() {}

func (x *ChangePasswordResponseMessage) ProtoReflect() protoreflect.Message {
	mi := &file_auth_grpc_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangePasswordResponseMessage.ProtoReflect.Descriptor instead.
func (*ChangePasswordResponseMessage) Descriptor() ([]byte, []int) {
	return file_auth_grpc_proto_rawDescGZIP(), []int{15}
}

func (x *ChangePasswordResponseMessage) GetRes() *Result {
	if x != nil {
		return x.Res
	}
	return nil
}

var File_auth_grpc_proto protoreflect.FileDescriptor

const file_auth_grpc_proto_rawDesc = "" +
	"\n" +
	"\x0fauth_grpc.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"E\n" +
	"\x14ClientIdentification\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x02 \x01(\tR\tuserAgent\"U\n" +
	"\bUserData\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\"6\n" +
	"\x06Result\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xb9\x01\n" +
	"\x1dRegisterAccountRequestMessage\x12J\n" +
	"\x15client_identification\x18\x01 \x01(\v2\x15.ClientIdentificationR\x14clientIdentification\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\"\xdf\x01\n" +
	"\x05Token\x12#\n" +
	"\rsession_token\x18\x01 \x01(\tR\fsessionToken\x12\x1d\n" +
	"\n" +
	"csrf_token\x18\x02 \x01(\tR\tcsrfToken\x12?\n" +
	"\n" +
	"expiration\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\n" +
	"expiration\x88\x01\x01\x127\n" +
	"\x06issued\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampH\x01R\x06issued\x88\x01\x01B\r\n" +
	"\v_expirationB\t\n" +
	"\a_issued\"h\n" +
	"\x1eRegisterAccountResponseMessage\x12\x19\n" +
	"\x03res\x18\x01 \x01(\v2\a.ResultR\x03res\x12!\n" +
	"\x05token\x18\x02 \x01(\v2\x06.TokenH\x00R\x05token\x88\x01\x01B\b\n" +
	"\x06_token\"\x93\x01\n" +
	"\x13LoginRequestMessage\x12J\n" +
	"\x15client_identification\x18\x01 \x01(\v2\x15.ClientIdentificationR\x14clientIdentification\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\"\x8b\x01\n" +
	"\x14LoginResponseMessage\x12\x19\n" +
	"\x03res\x18\x01 \x01(\v2\a.ResultR\x03res\x12!\n" +
	"\x05token\x18\x02 \x01(\v2\x06.TokenH\x00R\x05token\x88\x01\x01\x12\"\n" +
	"\x04user\x18\x03 \x01(\v2\t.UserDataH\x01R\x04user\x88\x01\x01B\b\n" +
	"\x06_tokenB\a\n" +
	"\x05_user\"8\n" +
	"\x18CheckTokenRequestMessage\x12\x1c\n" +
	"\x05token\x18\x01 \x01(\v2\x06.TokenR\x05token\"\x8b\x01\n" +
	"\x19CheckTokenResponseMessage\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12!\n" +
	"\x05token\x18\x02 \x01(\v2\x06.TokenH\x00R\x05token\x88\x01\x01\x12\"\n" +
	"\x04user\x18\x03 \x01(\v2\t.UserDataH\x01R\x04user\x88\x01\x01B\b\n" +
	"\x06_tokenB\a\n" +
	"\x05_user\"\xc2\x01\n" +
	"\x1aConfirmEmailRequestMessage\x12J\n" +
	"\x15client_identification\x18\x01 \x01(\v2\x15.ClientIdentificationR\x14clientIdentification\x126\n" +
	"\x17email_confirmation_code\x18\x02 \x01(\tR\x15emailConfirmationCode\x12\x17\n" +
	"\x04data\x18\x03 \x01(\tH\x00R\x04data\x88\x01\x01B\a\n" +
	"\x05_data\"\x92\x01\n" +
	"\x1bConfirmEmailResponseMessage\x12\x19\n" +
	"\x03res\x18\x01 \x01(\v2\a.ResultR\x03res\x12!\n" +
	"\x05token\x18\x02 \x01(\v2\x06.TokenH\x00R\x05token\x88\x01\x01\x12\"\n" +
	"\x04user\x18\x03 \x01(\v2\t.UserDataH\x01R\x04user\x88\x01\x01B\b\n" +
	"\x06_tokenB\a\n" +
	"\x05_user\"\xa2\x01\n" +
	"\x19ChangeEmailRequestMessage\x12J\n" +
	"\x15client_identification\x18\x01 \x01(\v2\x15.ClientIdentificationR\x14clientIdentification\x12\x1b\n" +
	"\tnew_email\x18\x02 \x01(\tR\bnewEmail\x12\x1c\n" +
	"\x05token\x18\x03 \x01(\v2\x06.TokenR\x05token\"7\n" +
	"\x1aChangeEmailResponseMessage\x12\x19\n" +
	"\x03res\x18\x01 \x01(\v2\a.ResultR\x03res\"\xad\x01\n" +
	"\x1cChangePasswordRequestMessage\x12J\n" +
	"\x15client_identification\x18\x01 \x01(\v2\x15.ClientIdentificationR\x14clientIdentification\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12!\n" +
	"\x05token\x18\x03 \x01(\v2\x06.TokenH\x00R\x05token\x88\x01\x01B\b\n" +
	"\x06_token\":\n" +
	"\x1dChangePasswordResponseMessage\x12\x19\n" +
	"\x03res\x18\x01 \x01(\v2\a.ResultR\x03res2\xc5\x03\n" +
	"\x04Auth\x12T\n" +
	"\x0fRegisterAccount\x12\x1e.RegisterAccountRequestMessage\x1a\x1f.RegisterAccountResponseMessage\"\x00\x126\n" +
	"\x05Login\x12\x14.LoginRequestMessage\x1a\x15.LoginResponseMessage\"\x00\x12E\n" +
	"\n" +
	"CheckToken\x12\x19.CheckTokenRequestMessage\x1a\x1a.CheckTokenResponseMessage\"\x00\x12K\n" +
	"\fConfirmEmail\x12\x1b.ConfirmEmailRequestMessage\x1a\x1c.ConfirmEmailResponseMessage\"\x00\x12H\n" +
	"\vChangeEmail\x12\x1a.ChangeEmailRequestMessage\x1a\x1b.ChangeEmailResponseMessage\"\x00\x12Q\n" +
	"\x0eChangePassword\x12\x1d.ChangePasswordRequestMessage\x1a\x1e.ChangePasswordResponseMessage\"\x00B\rZ\v./auth_grpcb\x06proto3"

var (
	file_auth_grpc_proto_rawDescOnce sync.Once
	file_auth_grpc_proto_rawDescData []byte
)

func file_auth_grpc_proto_rawDescGZIP() []byte {
	file_auth_grpc_proto_rawDescOnce.Do(func() {
		file_auth_grpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_grpc_proto_rawDesc), len(file_auth_grpc_proto_rawDesc)))
	})
	return file_auth_grpc_proto_rawDescData
}

var file_auth_grpc_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_auth_grpc_proto_goTypes = []any{
	(*ClientIdentification)(nil),           // 0: ClientIdentification
	(*UserData)(nil),                       // 1: UserData
	(*Result)(nil),                         // 2: Result
	(*RegisterAccountRequestMessage)(nil),  // 3: RegisterAccountRequestMessage
	(*Token)(nil),                          // 4: Token
	(*RegisterAccountResponseMessage)(nil), // 5: RegisterAccountResponseMessage
	(*LoginRequestMessage)(nil),            // 6: LoginRequestMessage
	(*LoginResponseMessage)(nil),           // 7: LoginResponseMessage
	(*CheckTokenRequestMessage)(nil),       // 8: CheckTokenRequestMessage
	(*CheckTokenResponseMessage)(nil),      // 9: CheckTokenResponseMessage
	(*ConfirmEmailRequestMessage)(nil),     // 10: ConfirmEmailRequestMessage
	(*ConfirmEmailResponseMessage)(nil),    // 11: ConfirmEmailResponseMessage
	(*ChangeEmailRequestMessage)(nil),      // 12: ChangeEmailRequestMessage
	(*ChangeEmailResponseMessage)(nil),     // 13: ChangeEmailResponseMessage
	(*ChangePasswordRequestMessage)(nil),   // 14: ChangePasswordRequestMessage
	(*ChangePasswordResponseMessage)(nil),  // 15: ChangePasswordResponseMessage
	(*timestamppb.Timestamp)(nil),          // 16: google.protobuf.Timestamp
}
var file_auth_grpc_proto_depIdxs = []int32{
	0,  // 0: RegisterAccountRequestMessage.client_identification:type_name -> ClientIdentification
	16, // 1: Token.expiration:type_name -> google.protobuf.Timestamp
	16, // 2: Token.issued:type_name -> google.protobuf.Timestamp
	2,  // 3: RegisterAccountResponseMessage.res:type_name -> Result
	4,  // 4: RegisterAccountResponseMessage.token:type_name -> Token
	0,  // 5: LoginRequestMessage.client_identification:type_name -> ClientIdentification
	2,  // 6: LoginResponseMessage.res:type_name -> Result
	4,  // 7: LoginResponseMessage.token:type_name -> Token
	1,  // 8: LoginResponseMessage.user:type_name -> UserData
	4,  // 9: CheckTokenRequestMessage.token:type_name -> Token
	4,  // 10: CheckTokenResponseMessage.token:type_name -> Token
	1,  // 11: CheckTokenResponseMessage.user:type_name -> UserData
	0,  // 12: ConfirmEmailRequestMessage.client_identification:type_name -> ClientIdentification
	2,  // 13: ConfirmEmailResponseMessage.res:type_name -> Result
	4,  // 14: ConfirmEmailResponseMessage.token:type_name -> Token
	1,  // 15: ConfirmEmailResponseMessage.user:type_name -> UserData
	0,  // 16: ChangeEmailRequestMessage.client_identification:type_name -> ClientIdentification
	4,  // 17: ChangeEmailRequestMessage.token:type_name -> Token
	2,  // 18: ChangeEmailResponseMessage.res:type_name -> Result
	0,  // 19: ChangePasswordRequestMessage.client_identification:type_name -> ClientIdentification
	4,  // 20: ChangePasswordRequestMessage.token:type_name -> Token
	2,  // 21: ChangePasswordResponseMessage.res:type_name -> Result
	3,  // 22: Auth.RegisterAccount:input_type -> RegisterAccountRequestMessage
	6,  // 23: Auth.Login:input_type -> LoginRequestMessage
	8,  // 24: Auth.CheckToken:input_type -> CheckTokenRequestMessage
	10, // 25: Auth.ConfirmEmail:input_type -> ConfirmEmailRequestMessage
	12, // 26: Auth.ChangeEmail:input_type -> ChangeEmailRequestMessage
	14, // 27: Auth.ChangePassword:input_type -> ChangePasswordRequestMessage
	5,  // 28: Auth.RegisterAccount:output_type -> RegisterAccountResponseMessage
	7,  // 29: Auth.Login:output_type -> LoginResponseMessage
	9,  // 30: Auth.CheckToken:output_type -> CheckTokenResponseMessage
	11, // 31: Auth.ConfirmEmail:output_type -> ConfirmEmailResponseMessage
	13, // 32: Auth.ChangeEmail:output_type -> ChangeEmailResponseMessage
	15, // 33: Auth.ChangePassword:output_type -> ChangePasswordResponseMessage
	28, // [28:34] is the sub-list for method output_type
	22, // [22:28] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_auth_grpc_proto_init() }
func file_auth_grpc_proto_init() {
	if File_auth_grpc_proto != nil {
		return
	}
	file_auth_grpc_proto_msgTypes[4].OneofWrappers = []any{}
	file_auth_grpc_proto_msgTypes[5].OneofWrappers = []any{}
	file_auth_grpc_proto_msgTypes[7].OneofWrappers = []any{}
	file_auth_grpc_proto_msgTypes[9].OneofWrappers = []any{}
	file_auth_grpc_proto_msgTypes[10].OneofWrappers = []any{}
	file_auth_grpc_proto_msgTypes[11].OneofWrappers = []any{}
	file_auth_grpc_proto_msgTypes[14].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_grpc_proto_rawDesc), len(file_auth_grpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auth_grpc_proto_goTypes,
		DependencyIndexes: file_auth_grpc_proto_depIdxs,
		MessageInfos:      file_auth_grpc_proto_msgTypes,
	}.Build()
	File_auth_grpc_proto = out.File
	file_auth_grpc_proto_goTypes = nil
	file_auth_grpc_proto_depIdxs = nil
}
