FROM golang:1.25-alpine

RUN apk add --no-cache git gcompat bash make protoc coreutils

WORKDIR /app

RUN go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
RUN go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest

COPY ./src/ ./src/
COPY ./proto/ ./proto/
COPY ./Makefile .

RUN chmod +x /app/proto/generate.sh
RUN dos2unix /app/proto/generate.sh

EXPOSE 8082
EXPOSE 9191

RUN make game-server
CMD ["/app/bin/game-server"]
